apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-tracker-config
  namespace: expense-tracker
data:
  PORT: "3000"
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "expense_tracker"
  DB_SSL_MODE: "disable"
  CORS_ORIGINS: "*"
