apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expense-tracker-ingress
  namespace: expense-tracker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: expense-tracker.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: expense-tracker-svc
                port:
                  number: 80
